all:
	g++ -std=c++11 \
		main.cpp \
		board.cpp \
		textutils.cpp \
		CellColors.cpp \
		cursor.cpp \
		screenutil.cpp \
		mouse.cpp \
		transform.cpp \
		util.cpp \
		highlight.cpp \
		debug.cpp \
		gun.cpp \
		keyboard.cpp \
		testbuilding.cpp \
		world.cpp \
		timer.cpp \
		base_actor.cpp \
		monster.cpp \
		-lGL \
		-lglut \
		-o ../bin/goonr
