all:
	g++ -std=c++11 \
		main.cpp \
		board.cpp \
		textutils.cpp \
		CellColors.cpp \
		cursor.cpp \
		screenutil.cpp \
		mouse.cpp \
		transform.cpp \
		util.cpp \
		highlight.cpp \
		debug.cpp \
		gun.cpp \
		-lGL \
		-lglut \
		-o ../bin/goonr
